### ISSUE TITLE
Windows + python3.9 + OpenVoice v2 = not possible without CUDA?

### ISSUE THREAD

**Issue by dusekdan** [myshell-ai/OpenVoice#188]
Hi,

I followed the windows installation guide, and tried both on latest python 3.12 and 3.9.12 (per recommendation from the guide for python to be 3.9).

When I attempt to run the v2 example from `demo_part3.ipynb`, I am getting error originating from the following line: 

`target_se, audio_name = se_extractor.get_se(reference_speaker, tone_color_converter, vad=False)`

This is the error:

```
Traceback (most recent call last):
  File "C:\Users\user\Source\VoiceCloningTests\OpenVoice\demov2_.py", line 23, in <module>
    target_se, audio_name = se_extractor.get_se(reference_speaker, tone_color_converter, vad=False)
  File "C:\Users\user\Source\VoiceCloningTests\OpenVoice\openvoice\se_extractor.py", line 146, in get_se
    wavs_folder = split_audio_whisper(audio_path, target_dir=target_dir, audio_name=audio_name)
  File "C:\Users\user\Source\VoiceCloningTests\OpenVoice\openvoice\se_extractor.py", line 22, in split_audio_whisper
    model = WhisperModel(model_size, device="cuda", compute_type="float16")
  File "C:\Users\user\Source\VoiceCloningTests\OpenVoice\env39\lib\site-packages\faster_whisper\transcribe.py", line 128, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version
```

In the beginning of my script - I follow the demo and setup my `device` variable in the same way to fallback to `cpu`. When I open the `se_extractor.py` file from the error above, I see that a device is hardcoded to be CUDA. And I end up with the error above. 

My device is using integrated graphics from Intel, so afaik it is not even CUDA-enabled. Does this mean I cannot run OpenVoice v2, without NVidia graphics?

This is [the code from the library - se_extractor.py -](https://github.com/myshell-ai/OpenVoice/blob/ce65d67b321dd9bc134d2d08dd7fa6b7e3e8b2c1/openvoice/se_extractor.py#L22) with hardcoded cuda string, that raises the issue:

```python
def split_audio_whisper(audio_path, audio_name, target_dir='processed'):
    global model
    if model is None:
        model = WhisperModel(model_size, device="cuda", compute_type="float16")
    # ... 
```

**Comment by jicka** [comment]
Hello,

I just ran into the same issue. I replaced the line in question with:
        model = WhisperModel(model_size, device="cpu", compute_type="float32")

And it works. Hope it helps you too !

**Comment by dusekdan** [comment]
Lol, just came back to say I iterated towards the same solution and got it working. Thanks for the tip.

For all those who will come to this issue looking for the same, here's how I iterated towards the solution:

1. I looked up through the files raising this problem. In code above, you can see it comes from `WhisperModel`.
2. I located the WhisperModel in my environment (installed by pip into virtualenv) in `venv/Lib/site-packages/faster_whisper` - I know it's in the faster_whisper module, because the `WhisperModel` is imported in the very beginning of the example from this module.
3. Error came from `transcribe.py`, so that's the file I open and look for class definition

Now there are two parameters of interest there - `device` and `compute_type`. When I previously just tried hardcoding `cpu` for device, I would end up being told `float16` is unsupported. So, my line of thinking was that I will look for what other types are supported and try their combinations.

Line 91 in transcribe contains a really long comment, out of which I will take out the most important parts:

```python
"""
Initializes the Whisper model.

        Args:
          [...]
          device: Device to use for computation ("cpu", "cuda", "auto").
          compute_type: Type to use for computation.
            See https://opennmt.net/CTranslate2/quantization.html.
          [...]
"""
```

[Quantization link](https://opennmt.net/CTranslate2/quantization.html) provides a reference table of implicit type conversions on load, in which I was able to look up what is the default value for CPU for `float16`, in my architecture (Intel, x64, it is `float32`).

I changed the corresponding line to hardcode `cpu` for `device` variable and `float32` for `compute_type` and got result on the output.

Reference table for your convenience:
![image](https://github.com/myshell-ai/OpenVoice/assets/6360711/3aaf6d88-01ad-42d3-a551-cd65793ed5ee)

**Comment by jicka** [comment]
haha you went about it much more professionally than I did :)
Happy we both found a solution.

**Comment by mambari** [comment]
Hello, I have the same error even with the fix :
![image](https://github.com/myshell-ai/OpenVoice/assets/10997358/4311c256-079d-44f4-aadb-350de0d3583c)

**Comment by hanarotg** [comment]
> Hello, I have the same error even with the fix : ![image](https://private-user-images.githubusercontent.com/10997358/326292395-4311c256-079d-44f4-aadb-350de0d3583c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODgyMjgsIm5iZiI6MTcyNzc4NzkyOCwicGF0aCI6Ii8xMDk5NzM1OC8zMjYyOTIzOTUtNDMxMWMyNTYtMDc5ZC00NGY0LWFhZGItMzUwZGUwZDM1ODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDEzMDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGY1YjY2NzI0ZmExZWI4ZjZlODVkNDI2NTYxMjY4YWM5MDIwMTM2YWFhMmU2ZDNkNzk4ODQyMzI0Y2ZmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LlZOU5UUVJMbA_Gnc-vC-fPfAPC0W94IVGMfz5xzXFM)

Hi @mambari , did you find any solutions about this problem? same error occur to me.

**Comment by jaliyasu** [comment]
When this is run in a Windows environment, it may encounter several issues. 
When vad=True:
### Issues Found -1
File not found when using "from whisper_timestamped.transcribe import get_audio_tensor"
## Solution will be installed FFmpeg on Windows # link https://github.com/BtbN/FFmpeg-Builds/releases
    # Add FFmpeg bin file to system path

### Issues Found-2
RuntimeError: Problem when installing silero with version None
## install uv pip install silero-vad
## Or using script as a Python file
