### ISSUE TITLE
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by JIers001** [myshell-ai/OpenVoice#92]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
My cuda is 11.8.  
How can solve it if I don't want to reinstall my cuda? (Other virtual environments rely on cuda11.8.)
More information:
Traceback (most recent call last):
  File "/home/km/OpenVoice/OpenVoice-main/openvoice.py", line 33, in <module>
    tone_color_converter.convert(
  File "/home/km/OpenVoice/OpenVoice-main/api.py", line 149, in convert
    spec = spectrogram_torch(y, hps.data.filter_length,
  File "/home/km/OpenVoice/OpenVoice-main/mel_processing.py", line 61, in spectrogram_torch
    spec = torch.stft(
  File "/home/km/miniconda3/envs/openvoice/lib/python3.9/site-packages/torch/functional.py", line 632, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by rlenain** [comment]
Hi there -- I get the same issue

**Comment by rlenain** [comment]
Fixed with 

```
pip install torch==2.0.1
pip install wavmark==0.0.3
```

**Comment by JIers001** [comment]
Thanks. The error above was addressed.
But a new issue arises.
My cuda is 11.2 (11.8 is wrong). Cudnn is 8.1. 
Is it possible for me to fix this problem without reinstalling cuda and cudnn?
Error information:
RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 5, 0) but found runtime version (8, 1, 0). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.Looks like your LD_LIBRARY_PATH contains incompatible version of cudnnPlease either remove it from the path or install cudnn (8, 5, 0)
Thanks again.

**Comment by naseerfaheem** [comment]
@rlenain I tried that, now it's complaining about Silero :

OSError                                   Traceback (most recent call last)
File [~/anaconda3/envs/openvoice/lib/python3.9/site-packages/whisper_timestamped/transcribe.py:1885](https://vscode-remote+ssh-002dremote-002b192-002e168-002e10-002e202.vscode-resource.vscode-cdn.net/home/naseer/datadrive/datascience/practice/openvoice/OpenVoice/~/anaconda3/envs/openvoice/lib/python3.9/site-packages/whisper_timestamped/transcribe.py:1885), in get_vad_segments(audio, output_sample, min_speech_duration, min_silence_duration, dilatation, method)
   [1884](https://vscode-remote+ssh-002dremote-002b192-002e168-002e10-002e202.vscode-resource.vscode-cdn.net/home/naseer/datadrive/datascience/practice/openvoice/OpenVoice/~/anaconda3/envs/openvoice/lib/python3.9/site-packages/whisper_timestamped/transcribe.py:1884) try:
-> [1885](https://vscode-remote+ssh-002dremote-002b192-002e168-002e10-002e202.vscode-resource.vscode-cdn.net/home/naseer/datadrive/datascience/practice/openvoice/OpenVoice/~/anaconda3/envs/openvoice/lib/python3.9/site-packages/whisper_timestamped/transcribe.py:1885)     _silero_vad_model, utils = torch.hub.load(repo_or_dir=repo_or_dir, model="silero_vad", onnx=onnx, source=source)
...
-> [1889](https://vscode-remote+ssh-002dremote-002b192-002e168-002e10-002e202.vscode-resource.vscode-cdn.net/home/naseer/datadrive/datascience/practice/openvoice/OpenVoice/~/anaconda3/envs/openvoice/lib/python3.9/site-packages/whisper_timestamped/transcribe.py:1889)     raise RuntimeError(f"Problem when installing silero with version {version}. Check versions here: https://github.com/snakers4/silero-vad/wiki/Version-history-and-Available-Models") from err
   [1890](https://vscode-remote+ssh-002dremote-002b192-002e168-002e10-002e202.vscode-resource.vscode-cdn.net/home/naseer/datadrive/datascience/practice/openvoice/OpenVoice/~/anaconda3/envs/openvoice/lib/python3.9/site-packages/whisper_timestamped/transcribe.py:1890) finally:
   [1891](https://vscode-remote+ssh-002dremote-002b192-002e168-002e10-002e202.vscode-resource.vscode-cdn.net/home/naseer/datadrive/datascience/practice/openvoice/OpenVoice/~/anaconda3/envs/openvoice/lib/python3.9/site-packages/whisper_timestamped/transcribe.py:1891)     if need_folder_hack:

RuntimeError: Problem when installing silero with version None. Check versions here: https://github.com/snakers4/silero-vad/wiki/Version-history-and-Available-Models

**Comment by jayavanth** [comment]
This worked for me 

`conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=12.1 -c pytorch -c nvidia`

I have 12.1 installed so I just bumped the version
